apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: example-self-hosted-saas-app
  namespace: example-self-hosted-saas-app
spec:
  imageRepositoryRef:
    name: example-self-hosted-saas-app
  policy:
    pattern:
      regexp: "^[a-f0-9]{40}$"
